---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devuser
  namespace: dev-env

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dev-env-devuser-full-access
  namespace: dev-env
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dev-env-devuser-view
  namespace: dev-env
subjects:
- kind: ServiceAccount
  name: devuser
  namespace: dev-env
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-env-devuser-full-access
