apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: mysql-service
  selector:
    app: mysql 
  type: ClusterIP
  sessionAffinity: ClientIP
