---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: produser
  namespace: prodenv

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prodenv-produser-full-access
  namespace: prodenv
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prodenv-produser-view
  namespace: prodenv
subjects:
- kind: ServiceAccount
  name: produser
  namespace: prodenv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prodenv-produser-full-access
