apiVersion: v1
kind: Service
metadata:
    name: wordpress-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: wordpress-service
  selector:
    app: wordpress 
  type: LoadBalancer
  sessionAffinity: ClientIP
